#!/bin/bash

# This scripts should not be executed!
# It is only to be called internally
# by its parent script "cluster.sh"


if [[ $# -eq 2 ]]; then    
    for i in `seq 1 ${1}`
    do
        MIN=$(($i-1))
        MAX=$i

        RANGE="$MIN:$MAX"
        TITLE="Tab $i - Range $RANGE"

        gnome-terminal --tab -t "$TITLE" -- npm run cli -- --join ${2} --range $RANGE
    done
else
    for i in `seq 1 ${1}`
    do
        gnome-terminal --tab -t "Tab $i" -- npm run cli --
    done
fi

